# Specify the package name 
package: testci

platform: 
  - osx-64
engine:
  - python=2.6

test:
  # Here I am using the posix bash shell just to show that this is posix
  #, but this can be a any bash command or just 'echo Hello ...'
  - bash -c 'echo Hello Posix World'
  - conda install nose
  - nosetests --with-xunit

script:
  - conda build .

# Tell the build worker we want to upload the resulting conda package
build_targets: conda

channels:
  - foo
  - bar


##########################################################################################
# Advanced Note
# Since echo is the same for windoes as is it for posix, we could remove the '---' document 
# seporator and the following .binstar.yaml configuration would work as well.
##########################################################################################

# package: testci
# platform: 
#   - win-64
#   - linux-64
#   - osx-64
# test:
#   - echo Hello Windows or Posix Command
#   - conda build .
# build_targets: conda
