
package: testci

build:
  number: 1

platform:
  #  - win-32
  # - win-64
  # - osx-64
  - linux-64
engine:
  - python=2.7

# before_environment:
#   - curl ifconfig.co
  # - conda config --add channels auto
  # - conda config --remove channels defaults --force
  # - conda config --set channel_alias http://192.168.87.1:4990/conda

# test:
  # Here I am using the posix bash shell just to show that this is posix
  #, but this can be a any bash command or just 'echo Hello ...'
  # - echo Hello Posix World'
  # - conda install nose
  # - nosetests --with-xunit

script:
  - env
  # - conda build .
  # - echo $BINSTAR_API_TOKEN
  # - echo $BINSTAR_API_SITE

# Tell the build worker we want to upload the resulting conda package
build_targets:
  files: conda
  channels:
    - $GIT_BRANCH

