notifications:
  email: 
    recipients: sean
    on_success: always # default is change
---

package: testci
platform: 
  - osx-64
engine:
  - python=2

before_script:
  - python -V
  - conda install -q setuptools pip
  - pip install coverage -q

script:
  - python setup.py develop
  - python testci/tests/runtests.py --html
  - python setup.py sdist

build_targets: pypi

build_artifacts:
  - coverage
