# Specify the package name 
package: testci

build:
  number: 1

platform:
  - linux-64
engine:
  - python=2.7

test:
  # Here I am using the posix bash shell just to show that this is posix
  #, but this can be a any bash command or just 'echo Hello ...'
  - bash -c 'echo Hello Posix World'
  - conda install nose
  - nosetests --with-xunit

script:
  - conda build .
  - env
  # - echo $BINSTAR_API_TOKEN
  # - echo $BINSTAR_API_SITE

# Tell the build worker we want to upload the resulting conda package
build_targets:
  files: conda
  channels: [foo, bar]

