package: testci
platform: 
  - linux-32
  - linux-64
engine:
  - python=2
  - python=3

before_script:
  - python -V
  - conda install -q setuptools pip
  - pip install coverage -q

script:
  - python setup.py develop
  - python testci/tests/runtests.py --html

build_artifacts:
  - coverage
