package: testci
platform: 
  - linux-64
engine:
  - python=2
  - python=3

before_script:
  - conda install setuptools
  - conda install pip
  - pip install coverage

script:
  - python setup.py develop
  - python -m unittest discover
