package:
  name: testci
  version: 1.0.0

build:
  number: {{environ.get('BINSTAR_BUILD_MAJOR', 1)}}
  noarch_python: true


requirements:
  run:
    - python


about:
  summary: This is a simple package to test binstar-build

